#!/bin/bash

provider "aws" {
  region = "us-east-1"
}

resource "aws_instance" "example" {
  ami           = "ami-0c7217cdde317cfec"
  instance_type = "t2.micro"
  key_name      = "nextgen-devops-team"
  subnet_id     = "subnet-09bb946c638fdd9a3"
  security_groups = [
    "nextgen-devops-sg",
  ]
}

resource "null_resource" "example" {
  provisioner "local-exec" {
    command = "echo 'Hello World!' > index.html"
  }
}

resource "aws_ebs" "example" {
  count = 1

  availability_zone = "us-east-1a"
  volume_type       = "gp2"
  size             = 30
}

resource "aws_instance" "example" {
  count = 1

  ami           = "ami-0c7217cdde317cfec"
  instance_type = "t2.micro"
  key_name      = "nextgen-devops-team"
  subnet_id     = "subnet-09bb946c638fdd9a3"
  security_groups = [
    "sg-0123456789",
  ]
}

resource "aws_key_pair" "example" {
  count = 1

  key_name      = "nextgen-devops-team"
  private_key = file("${var.private_key_path}")
}
